name: 'Webhook Slack Notify'
description: 'This action will send a notification to Slack'
author: 'ofirshtrull'
runs:
  using: 'docker'
  image: 'docker://ofirshtrull/action-webhook-slack-notify:v0.0.2'
branding:
  icon: 'code'
  color: 'red'
